LD_LIYI = {
[1] = {id = 1, question = "乱斗英雄传游戏中不能干什么？", deshero = 242, 
	answers = {{order = 1, select = "爆刷深渊培养队伍", answer = 0}, {order = 2, select = "设计制作自己脑洞的事件或者装备", answer = 0}, {order = 3, select = "休闲挂机轻松养成", answer = 0}, {order = 4, select = "在游戏中和其他团长互喷", answer = 1}}}, 
[2] = {id = 2, question = "填ta的推荐人的理由，哪一条是错的？", deshero = 242, 
	answers = {{order = 1, select = "ta是能够给你讲解的老司机", answer = 0}, {order = 2, select = "ta是你的好朋友", answer = 0}, {order = 3, select = "ta能和你一起吐槽乱斗英雄传", answer = 0}, {order = 4, select = "ta对你使用了王的微笑试图进行“传销”", answer = 1}}}, 
[3] = {id = 3, question = "当游戏中遇到bug，怎样反馈最有效？", deshero = 242, 
	answers = {{order = 1, select = "在游戏中不停发帖狂喷", answer = 0}, {order = 2, select = "召集好友殴打游戏作者", answer = 0}, {order = 3, select = "立刻联系客服小姐姐", answer = 1}, {order = 4, select = "其他三条都有效", answer = 0}}}, 
[4] = {id = 4, question = "游戏团队如果拖更了怎么办？", deshero = 242, 
	answers = {{order = 1, select = "搬个小板凳围观", answer = 0}, {order = 2, select = "打电话报警", answer = 0}, {order = 3, select = "去各大论坛狂刷666", answer = 0}, {order = 4, select = "及时联系客服寻求合理解答", answer = 1}}}, 
[5] = {id = 5, question = "如何才能在游戏中获得活跃经验？", deshero = 242, 
	answers = {{order = 1, select = "每日签到获得", answer = 0}, {order = 2, select = "完成每日日常任务后获得", answer = 0}, {order = 3, select = "推荐好友或者赞助一波", answer = 0}, {order = 4, select = "其他三条都可以", answer = 1}}}, 
[6] = {id = 6, question = "关于乱斗英雄传，哪一条是错的？", deshero = 242, 
	answers = {{order = 1, select = "游戏作者是蠢蛋", answer = 0}, {order = 2, select = "游戏中还有很多不足需要大家监督指正", answer = 0}, {order = 3, select = "游戏群中有很多大佬可以一起交流", answer = 0}, {order = 4, select = "这是一个滚服游戏", answer = 1}}}, 
[7] = {id = 7, question = "关于主角经验的描述，哪一条是错的？", deshero = 242, 
	answers = {{order = 1, select = "主角经验在事件、副本、佣兵营地战斗中自动获取", answer = 0}, {order = 2, select = "主角经验获取时自动增加当前主角经验", answer = 0}, {order = 3, select = "可以通过商店兑换道具增加主角经验", answer = 0}, {order = 4, select = "主角经验等于英雄经验", answer = 1}}}, 
[8] = {id = 8, question = "关于升星的描述，哪一条是错的？", deshero = 242, 
	answers = {{order = 1, select = "升星可以提高英雄的四维", answer = 0}, {order = 2, select = "在英雄升到满级后升级按钮变为升星按钮", answer = 0}, {order = 3, select = "通过消耗相同星级和类型的英雄来升级", answer = 0}, {order = 4, select = "升星之后英雄的进攻欲望会变强", answer = 1}}}, 
[9] = {id = 9, question = "速度和耐力（鞋子）的关系，哪一个是错的？", deshero = 242, 
	answers = {{order = 1, select = "速度和耐力是同一个数值", answer = 1}, {order = 2, select = "速度能够提升耐力的恢复速度", answer = 0}, {order = 3, select = "100点速度提高1%恢复速度", answer = 0}, {order = 4, select = "双方速度差距越大，耐力的恢复量差距越大", answer = 0}}}, 
[10] = {id = 10, question = "关于战斗时血条下面资源的描述哪个是不正确的？", deshero = 242, 
	answers = {{order = 1, select = "当双方@icon_naili@耐力都恢复到100点或其他三条时才开始计算出手", answer = 0}, {order = 2, select = ".@icon_nuqi@怒气，@icon_nengliang2@能量，@icon_fali2@法力值影响某些技能的释放", answer = 0}, {order = 3, select = "游戏开始时双方会获得一个小范围随机的初始耐力值", answer = 0}, {order = 4, select = "所有资源没有使用限制", answer = 1}}}, 
[11] = {id = 11, question = "技能序列和连招器的描述，哪个是正确的？", deshero = 242, 
	answers = {{order = 1, select = "当该回合配置连招时，优先释放连招技能", answer = 0}, {order = 2, select = "连招技能的触发回合为：初始冷却+n*冷却时间", answer = 0}, {order = 3, select = "连招技能会受到消耗的怒气、能量、法力限制，但是不会受到耐力的限制", answer = 0}, {order = 4, select = "其他三条都正确", answer = 1}}}, 
[12] = {id = 12, question = "关于行动时……被攻击时……等触发技能等描述，哪个是正确的？", deshero = 242, 
	answers = {{order = 1, select = "触发型的技能，一般对整个队伍都有效果", answer = 0}, {order = 2, select = "所有的概率都是独立计算的", answer = 0}, {order = 3, select = "除非有回合数或者层数限制，一般可以无限叠加", answer = 0}, {order = 4, select = "其他三条都正确", answer = 1}}}, 
[13] = {id = 13, question = "如果缺少钻石，哪一条是错误的？", deshero = 242, 
	answers = {{order = 1, select = "在公会中击败土地精", answer = 0}, {order = 2, select = "积极清扫事件", answer = 0}, {order = 3, select = "与朋友一起参与制作钻石事件", answer = 0}, {order = 4, select = "和客服小姐姐进行交易", answer = 1}}}, 
[14] = {id = 14, question = "关于技能石的描述，哪一条是错误的？", deshero = 242, 
	answers = {{order = 1, select = "技能石最直接的获取方式是分解英雄", answer = 0}, {order = 2, select = "游戏中有普通、史诗、传说、神话4种技能石", answer = 0}, {order = 3, select = "万能技能石适用于所有品质的英雄", answer = 0}, {order = 4, select = "每个英雄可以无限使用技能石", answer = 1}}}, 
[15] = {id = 15, question = "如果游戏中出现不理解的机制和属性，哪一条是错误的？", deshero = 242, 
	answers = {{order = 1, select = "勤点游戏中的i来进行查询", answer = 0}, {order = 2, select = "加入玩家群咨询大佬", answer = 0}, {order = 3, select = "在论坛上查看攻略", answer = 0}, {order = 4, select = "怒摔手机", answer = 1}}}}